server:
  port: 8050

spring:
  application:
    name: user-template
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Kết nối đến Eureka Server
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
